### ISSUE TITLE
Pull CI/CD setup into workshop setup

### ISSUE THREAD

**Issue by bahrmichael** [docker/labs#354]
Please provide the following information so we can assess the issue you're having

**Which lab is it that you're having issues with?**

https://github.com/docker/labs/blob/master/developer-tools/java/chapters/ch09-cicd.adoc

**Description**

Preparations from sub-chapter `Run Jenkins on Docker` take rather long, esp. with slow conference wifi. Pull them into the workshop prep steps or reference them there if possible.

**Suggestion**
In the [workshop setup instructions](https://github.com/docker/labs/blob/master/developer-tools/java/chapters/ch01-setup.adoc), add a note like "If you want to do the [CI/CD chapter](https://github.com/docker/labs/blob/master/developer-tools/java/chapters/ch09-cicd.adoc), we recommend to execute [these preparation steps](https://github.com/docker/labs/blob/master/developer-tools/java/chapters/ch09-cicd.adoc#run-jenkins-on-docker)."

@arun-gupta

**Comment by bahrmichael** [comment]
Especially from Step 5/11 it became rather slow.

```
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`.

Creating network "jenkinsdockerdemo_default" with the default driver
Building jenkins
Step 1/11 : FROM jenkins/jenkins:lts
lts: Pulling from jenkins/jenkins
3e17c6eae66c: Already exists
74d44b20f851: Already exists
a156217f3fa4: Already exists
4a1ed13b6faa: Already exists
77980e5d0a6d: Already exists
5458607a81d3: Already exists
e34cf8338f42: Already exists
2f3d3da5c56e: Already exists
2ade7a861e3f: Already exists
961606e5ce60: Pull complete
765b174f9a73: Pull complete
39571860b01f: Pull complete
70493c7554eb: Pull complete
577b27a786ce: Pull complete
4970f1d4d9c9: Pull complete
f4c333a8ab93: Pull complete
dc1e0fe1e0c8: Pull complete
2f8ccbfb7ea0: Pull complete
339f85fccb26: Pull complete
efdb24870862: Pull complete
Digest: sha256:025db2d00e5ba8b7a531e6d35513d6945854641977d2ab4ab21be79ac763d86f
Status: Downloaded newer image for jenkins/jenkins:lts
 ---> e6b6a36fca5a
Step 2/11 : USER root
 ---> Running in 1b849be2dd34
 ---> 73b19acfa8cc
Removing intermediate container 1b849be2dd34
Step 3/11 : RUN apt-get update       && apt-get install -y sudo       && rm -rf /var/lib/apt/lists/*
 ---> Running in e01aee185347
Ign:1 http://deb.debian.org/debian stretch InRelease
Get:2 http://deb.debian.org/debian stretch-updates InRelease [91.0 kB]
Get:3 http://security.debian.org stretch/updates InRelease [62.9 kB]
Get:4 http://deb.debian.org/debian stretch Release [118 kB]
Get:5 http://deb.debian.org/debian stretch-updates/main amd64 Packages [5841 B]
Get:6 http://deb.debian.org/debian stretch Release.gpg [2479 B]
Get:7 http://security.debian.org stretch/updates/main amd64 Packages [222 kB]
Get:8 http://deb.debian.org/debian stretch/main amd64 Packages [9500 kB]
Fetched 10.0 MB in 28s (347 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  sudo
0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
Need to get 1055 kB of archives.
After this operation, 3108 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian stretch/main amd64 sudo amd64 1.8.19p1-2.1 [1055 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 1055 kB in 3s (343 kB/s)
Selecting previously unselected package sudo.
(Reading database ... 29522 files and directories currently installed.)
Preparing to unpack .../sudo_1.8.19p1-2.1_amd64.deb ...
Unpacking sudo (1.8.19p1-2.1) ...
Setting up sudo (1.8.19p1-2.1) ...
 ---> eecff3a3369e
Removing intermediate container e01aee185347
Step 4/11 : RUN echo "jenkins ALL=NOPASSWD: ALL" >> /etc/sudoers
 ---> Running in 061e0a2fd647
 ---> ea6bc634b964
Removing intermediate container 061e0a2fd647
Step 5/11 : RUN curl -sSL https://get.docker.com/ | sh &&     apt-get purge -y docker-engine &&     apt-get install docker-ce
 ---> Running in 9e0f96f2f983
# Executing docker install script, commit: 490beaa
+ sh -c apt-get update -qq >/dev/null
+ sh -c apt-get install -y -qq apt-transport-https ca-certificates curl software-properties-common >/dev/null
debconf: delaying package configuration, since apt-utils is not installed
+ sh -c curl -fsSL "https://download.docker.com/linux/debian/gpg" | apt-key add -qq - >/dev/null
Warning: apt-key output should not be parsed (stdout is not a terminal)
+ sh -c echo "deb [arch=amd64] https://download.docker.com/linux/debian stretch edge" > /etc/apt/sources.list.d/docker.list
+ [ debian = debian ]
+ [ stretch = wheezy ]
+ sh -c apt-get update -qq >/dev/null
+ sh -c apt-get install -y -qq docker-ce >/dev/null
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
If you would like to use Docker as a non-root user, you should now consider
adding your user to the "docker" group with something like:

  sudo usermod -aG docker your-user

Remember that you will have to log out and back in for this to take effect!

WARNING: Adding a user to the "docker" group will grant the ability to run
         containers which can be used to obtain root privileges on the
         docker host.
         Refer to https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
         for more information.
Reading package lists...
Building dependency tree...
Reading state information...
Package 'docker-engine' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
docker-ce is already the newest version (17.09.0~ce-0~debian).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
 ---> 781a1f9d615c
Removing intermediate container 9e0f96f2f983
Step 6/11 : RUN curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose && 	chmod +x /usr/local/bin/docker-compose
 ---> Running in 1136f44a3228
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   617    0   617    0     0    164      0 --:--:--  0:00:03 --:--:--   164
100 8066k  100 8066k    0     0   363k      0  0:00:22  0:00:22 --:--:--  472k
 ---> ccec15f82c94
Removing intermediate container 1136f44a3228
Step 7/11 : RUN usermod -aG docker jenkins
 ---> Running in 8f75ddc64463
 ---> 56c536780e41
Removing intermediate container 8f75ddc64463
Step 8/11 : USER jenkins
 ---> Running in cfb41bb61feb
 ---> 6d614f71df86
Removing intermediate container cfb41bb61feb
Step 9/11 : COPY plugins.txt /usr/share/jenkins/plugins.txt
 ---> 64872a48ffb9
Step 10/11 : RUN /usr/local/bin/plugins.sh /usr/share/jenkins/plugins.txt
 ---> Running in 211654b33cfd
WARN: plugins.sh is deprecated, please switch to install-plugins.sh
Analyzing war: /usr/share/jenkins/jenkins.war
Downloading scm-api:latest
Downloading apache-httpcomponents-client-4-api:latest
Downloading credentials:latest
Downloading matrix-project:latest
Downloading display-url-api:latest
Downloading workflow-job:latest
Downloading token-macro:latest
Downloading junit:latest
Downloading script-security:latest
Downloading ssh-credentials:latest
Downloading workflow-scm-step:latest
Downloading workflow-step-api:latest
Downloading mailer:latest
Downloading structs:latest
Downloading jackson2-api:latest
Downloading git-client:latest
Downloading git:latest
Downloading plain-credentials:latest
Downloading github-api:latest
Downloading github:latest
Downloading jsch:latest
Downloading bouncycastle-api:latest
Downloading windows-slaves:latest
Downloading matrix-auth:latest
Downloading icon-shim:latest
Downloading maven-plugin:latest
Downloading javadoc:latest
Downloading maven-plugin:latest
Downloading postbuildscript:latest
---------------------------------------------------
INFO: Successfully installed 29 plugins.
---------------------------------------------------
 ---> 6f3bb205bb88
Removing intermediate container 211654b33cfd
Step 11/11 : COPY settings.xml /root/.m2/
 ---> 89df0cb99ee7
Successfully built 89df0cb99ee7
Successfully tagged tail/jenkins:lts
WARNING: Image for service jenkins was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating jenkinsdockerdemo_jenkins_1 ...
Creating jenkinsdockerdemo_jenkins_1 ... done
Attaching to jenkinsdockerdemo_jenkins_1
jenkins_1  | Running from: /usr/share/jenkins/jenkins.war
jenkins_1  | webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
jenkins_1  | Oct 16, 2017 1:35:48 PM Main deleteWinstoneTempContents
jenkins_1  | WARNING: Failed to delete the temporary Winstone file /tmp/winstone/jenkins.war
jenkins_1  | Oct 16, 2017 1:35:48 PM org.eclipse.jetty.util.log.Log initialized
jenkins_1  | INFO: Logging initialized @612ms to org.eclipse.jetty.util.log.JavaUtilLog
jenkins_1  | Oct 16, 2017 1:35:48 PM winstone.Logger logInternal
jenkins_1  | INFO: Beginning extraction from war file
jenkins_1  | Oct 16, 2017 1:35:56 PM org.eclipse.jetty.server.handler.ContextHandler setContextPath
jenkins_1  | WARNING: Empty contextPath
jenkins_1  | Oct 16, 2017 1:35:56 PM org.eclipse.jetty.server.Server doStart
jenkins_1  | INFO: jetty-9.4.z-SNAPSHOT
jenkins_1  | Oct 16, 2017 1:35:58 PM org.eclipse.jetty.webapp.StandardDescriptorProcessor visitServlet
jenkins_1  | INFO: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
jenkins_1  | Oct 16, 2017 1:35:58 PM org.eclipse.jetty.server.session.DefaultSessionIdManager doStart
jenkins_1  | INFO: DefaultSessionIdManager workerName=node0
jenkins_1  | Oct 16, 2017 1:35:58 PM org.eclipse.jetty.server.session.DefaultSessionIdManager doStart
jenkins_1  | INFO: No SessionScavenger set, using defaults
jenkins_1  | Oct 16, 2017 1:35:58 PM org.eclipse.jetty.server.session.HouseKeeper startScavenging
jenkins_1  | INFO: Scavenging every 660000ms
jenkins_1  | Jenkins home directory: /var/jenkins_home found at: EnvVars.masterEnvVars.get("JENKINS_HOME")
jenkins_1  | Oct 16, 2017 1:35:59 PM org.eclipse.jetty.server.handler.ContextHandler doStart
jenkins_1  | INFO: Started w.@5b58ed3c{/,file:///var/jenkins_home/war/,AVAILABLE}{/var/jenkins_home/war}
jenkins_1  | Oct 16, 2017 1:35:59 PM org.eclipse.jetty.server.AbstractConnector doStart
jenkins_1  | INFO: Started ServerConnector@649725e3{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
jenkins_1  | Oct 16, 2017 1:35:59 PM org.eclipse.jetty.server.Server doStart
jenkins_1  | INFO: Started @11584ms
jenkins_1  | Oct 16, 2017 1:35:59 PM winstone.Logger logInternal
jenkins_1  | INFO: Winstone Servlet Engine v4.0 running: controlPort=disabled
jenkins_1  | Oct 16, 2017 1:36:00 PM jenkins.InitReactorRunner$1 onAttained
jenkins_1  | INFO: Started initialization
jenkins_1  | Oct 16, 2017 1:36:09 PM hudson.ClassicPluginStrategy createClassJarFromWebInfClasses
jenkins_1  | WARNING: Created /var/jenkins_home/plugins/jsch/WEB-INF/lib/classes.jar; update plugin to a version created with a newer harness
jenkins_1  | Oct 16, 2017 1:36:15 PM jenkins.InitReactorRunner$1 onAttained
jenkins_1  | INFO: Listed all plugins
jenkins_1  | Oct 16, 2017 1:36:15 PM jenkins.InitReactorRunner$1 onTaskFailed
jenkins_1  | SEVERE: Failed Loading plugin Pipeline: Job v2.15 (workflow-job)
jenkins_1  | java.io.IOException: Pipeline: Job v2.15 failed to load.
jenkins_1  |  - workflow-api v2.15 is missing. To fix, install v2.15 or later.
jenkins_1  |  - workflow-support v2.14 is missing. To fix, install v2.14 or later.
jenkins_1  | 	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:626)
jenkins_1  | 	at hudson.PluginManager$2$1$1.run(PluginManager.java:516)
jenkins_1  | 	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
jenkins_1  | 	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
jenkins_1  | 	at jenkins.model.Jenkins$7.runTask(Jenkins.java:1090)
jenkins_1  | 	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
jenkins_1  | 	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
jenkins_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
jenkins_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
jenkins_1  | 	at java.lang.Thread.run(Thread.java:748)
jenkins_1  |
jenkins_1  | Oct 16, 2017 1:36:15 PM jenkins.InitReactorRunner$1 onTaskFailed
jenkins_1  | SEVERE: Failed Loading plugin Token Macro Plugin v2.3 (token-macro)
jenkins_1  | java.io.IOException: Token Macro Plugin v2.3 failed to load.
jenkins_1  |  - Pipeline: Job v2.15 failed to load. Fix this plugin first.
jenkins_1  | 	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:626)
jenkins_1  | 	at hudson.PluginManager$2$1$1.run(PluginManager.java:516)
jenkins_1  | 	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
jenkins_1  | 	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
jenkins_1  | 	at jenkins.model.Jenkins$7.runTask(Jenkins.java:1090)
jenkins_1  | 	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
jenkins_1  | 	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
jenkins_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
jenkins_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
jenkins_1  | 	at java.lang.Thread.run(Thread.java:748)
jenkins_1  |
jenkins_1  | Oct 16, 2017 1:36:15 PM jenkins.InitReactorRunner$1 onTaskFailed
jenkins_1  | SEVERE: Failed Loading plugin GitHub plugin v1.28.0 (github)
jenkins_1  | java.io.IOException: GitHub plugin v1.28.0 failed to load.
jenkins_1  |  - Token Macro Plugin v2.3 failed to load. Fix this plugin first.
jenkins_1  | 	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:626)
jenkins_1  | 	at hudson.PluginManager$2$1$1.run(PluginManager.java:516)
jenkins_1  | 	at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
jenkins_1  | 	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
jenkins_1  | 	at jenkins.model.Jenkins$7.runTask(Jenkins.java:1090)
jenkins_1  | 	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
jenkins_1  | 	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
jenkins_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
jenkins_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
jenkins_1  | 	at java.lang.Thread.run(Thread.java:748)
jenkins_1  |
jenkins_1  | Oct 16, 2017 1:36:18 PM hudson.ExtensionFinder$Sezpoz scout
jenkins_1  | WARNING: Failed to scout com.cloudbees.hudson.plugins.folder.properties.AuthorizationMatrixProperty$ItemListenerImpl
jenkins_1  | java.lang.NoClassDefFoundError: com/cloudbees/hudson/plugins/folder/AbstractFolder
jenkins_1  | 	at java.lang.Class.forName0(Native Method)
jenkins_1  | 	at java.lang.Class.forName(Class.java:348)
jenkins_1  | 	at hudson.ExtensionFinder$Sezpoz.scout(ExtensionFinder.java:669)
jenkins_1  | 	at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:473)
jenkins_1  | 	at hudson.ExtensionList.load(ExtensionList.java:365)
jenkins_1  | 	at hudson.ExtensionList.ensureLoaded(ExtensionList.java:303)
jenkins_1  | 	at hudson.ExtensionList.getComponents(ExtensionList.java:168)
jenkins_1  | 	at jenkins.model.Jenkins$8.onInitMilestoneAttained(Jenkins.java:1121)
jenkins_1  | 	at jenkins.InitReactorRunner$1.onAttained(InitReactorRunner.java:82)
jenkins_1  | 	at org.jvnet.hudson.reactor.ReactorListener$Aggregator.onAttained(ReactorListener.java:104)
jenkins_1  | 	at org.jvnet.hudson.reactor.Reactor$1.run(Reactor.java:176)
jenkins_1  | 	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
jenkins_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
jenkins_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
jenkins_1  | 	at java.lang.Thread.run(Thread.java:748)
jenkins_1  | Caused by: java.lang.ClassNotFoundException: com.cloudbees.hudson.plugins.folder.AbstractFolder
jenkins_1  | 	at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1374)
jenkins_1  | 	at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1327)
jenkins_1  | 	at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1080)
jenkins_1  | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
jenkins_1  | 	... 15 more
jenkins_1  |
jenkins_1  | Oct 16, 2017 1:36:19 PM hudson.ExtensionFinder$GuiceFinder$SezpozModule configure
jenkins_1  | WARNING: Failed to load com.cloudbees.hudson.plugins.folder.properties.AuthorizationMatrixProperty$ItemListenerImpl
jenkins_1  | java.lang.NoClassDefFoundError: com/cloudbees/hudson/plugins/folder/AbstractFolder
jenkins_1  | 	at java.lang.Class.getDeclaredConstructors0(Native Method)
jenkins_1  | 	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
jenkins_1  | 	at java.lang.Class.getConstructors(Class.java:1651)
jenkins_1  | 	at hudson.ExtensionFinder$GuiceFinder$SezpozModule.resolve(ExtensionFinder.java:476)
jenkins_1  | 	at hudson.ExtensionFinder$GuiceFinder$SezpozModule.configure(ExtensionFinder.java:506)
jenkins_1  | 	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
jenkins_1  | 	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
jenkins_1  | 	at com.google.inject.spi.Elements.getElements(Elements.java:110)
jenkins_1  | 	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
jenkins_1  | 	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
jenkins_1  | 	at com.google.inject.Guice.createInjector(Guice.java:96)
jenkins_1  | 	at com.google.inject.Guice.createInjector(Guice.java:73)
jenkins_1  | 	at hudson.ExtensionFinder$GuiceFinder.<init>(ExtensionFinder.java:280)
jenkins_1  | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
jenkins_1  | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
jenkins_1  | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
jenkins_1  | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
jenkins_1  | 	at java.lang.Class.newInstance(Class.java:442)
jenkins_1  | 	at net.java.sezpoz.IndexItem.instance(IndexItem.java:181)
jenkins_1  | 	at hudson.ExtensionFinder$Sezpoz._find(ExtensionFinder.java:634)
jenkins_1  | 	at hudson.ExtensionFinder$Sezpoz.find(ExtensionFinder.java:609)
jenkins_1  | 	at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:479)
jenkins_1  | 	at hudson.ExtensionList.load(ExtensionList.java:365)
jenkins_1  | 	at hudson.ExtensionList.ensureLoaded(ExtensionList.java:303)
jenkins_1  | 	at hudson.ExtensionList.getComponents(ExtensionList.java:168)
jenkins_1  | 	at jenkins.model.Jenkins$8.onInitMilestoneAttained(Jenkins.java:1121)
jenkins_1  | 	at jenkins.InitReactorRunner$1.onAttained(InitReactorRunner.java:82)
jenkins_1  | 	at org.jvnet.hudson.reactor.ReactorListener$Aggregator.onAttained(ReactorListener.java:104)
jenkins_1  | 	at org.jvnet.hudson.reactor.Reactor$1.run(Reactor.java:176)
jenkins_1  | 	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
jenkins_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
jenkins_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
jenkins_1  | 	at java.lang.Thread.run(Thread.java:748)
jenkins_1  | Caused by: java.lang.ClassNotFoundException: com.cloudbees.hudson.plugins.folder.AbstractFolder
jenkins_1  | 	at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1374)
jenkins_1  | 	at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1327)
jenkins_1  | 	at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1080)
jenkins_1  | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
jenkins_1  | 	... 33 more
jenkins_1  |
jenkins_1  | Oct 16, 2017 1:36:21 PM jenkins.InitReactorRunner$1 onAttained
jenkins_1  | INFO: Prepared all plugins
jenkins_1  | Oct 16, 2017 1:36:21 PM jenkins.InitReactorRunner$1 onAttained
jenkins_1  | INFO: Started all plugins
jenkins_1  | Oct 16, 2017 1:36:21 PM jenkins.InitReactorRunner$1 onAttained
jenkins_1  | INFO: Augmented all extensions
jenkins_1  | Oct 16, 2017 1:36:22 PM jenkins.InitReactorRunner$1 onAttained
jenkins_1  | INFO: Loaded all jobs
jenkins_1  | Oct 16, 2017 1:36:22 PM hudson.model.AsyncPeriodicWork$1 run
jenkins_1  | INFO: Started Download metadata
jenkins_1  | Oct 16, 2017 1:36:22 PM hudson.model.AsyncPeriodicWork$1 run
jenkins_1  | INFO: Finished Download metadata. 31 ms
jenkins_1  | Oct 16, 2017 1:36:22 PM jenkins.util.groovy.GroovyHookScript execute
jenkins_1  | INFO: Executing /var/jenkins_home/init.groovy.d/tcp-slave-agent-port.groovy
jenkins_1  | Oct 16, 2017 1:36:24 PM jenkins.InitReactorRunner$1 onAttained
jenkins_1  | INFO: Completed initialization
jenkins_1  | Oct 16, 2017 1:36:24 PM org.springframework.context.support.AbstractApplicationContext prepareRefresh
jenkins_1  | INFO: Refreshing org.springframework.web.context.support.StaticWebApplicationContext@61a73dcc: display name [Root WebApplicationContext]; startup date [Mon Oct 16 13:36:24 UTC 2017]; root of context hierarchy
jenkins_1  | Oct 16, 2017 1:36:24 PM org.springframework.context.support.AbstractApplicationContext obtainFreshBeanFactory
jenkins_1  | INFO: Bean factory for application context [org.springframework.web.context.support.StaticWebApplicationContext@61a73dcc]: org.springframework.beans.factory.support.DefaultListableBeanFactory@694526a
jenkins_1  | Oct 16, 2017 1:36:24 PM org.springframework.beans.factory.support.DefaultListableBeanFactory preInstantiateSingletons
jenkins_1  | INFO: Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@694526a: defining beans [authenticationManager]; root of factory hierarchy
jenkins_1  | Oct 16, 2017 1:36:25 PM org.springframework.context.support.AbstractApplicationContext prepareRefresh
jenkins_1  | INFO: Refreshing org.springframework.web.context.support.StaticWebApplicationContext@5a36a579: display name [Root WebApplicationContext]; startup date [Mon Oct 16 13:36:25 UTC 2017]; root of context hierarchy
jenkins_1  | Oct 16, 2017 1:36:25 PM org.springframework.context.support.AbstractApplicationContext obtainFreshBeanFactory
jenkins_1  | INFO: Bean factory for application context [org.springframework.web.context.support.StaticWebApplicationContext@5a36a579]: org.springframework.beans.factory.support.DefaultListableBeanFactory@6d107d66
jenkins_1  | Oct 16, 2017 1:36:25 PM org.springframework.beans.factory.support.DefaultListableBeanFactory preInstantiateSingletons
jenkins_1  | INFO: Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@6d107d66: defining beans [filter,legacy]; root of factory hierarchy
jenkins_1  | Oct 16, 2017 1:36:25 PM hudson.WebAppMain$3 run
jenkins_1  | INFO: Jenkins is fully up and running
jenkins_1  | --> setting agent port for jnlp
jenkins_1  | --> setting agent port for jnlp... done
jenkins_1  | Oct 16, 2017 1:37:09 PM org.eclipse.jetty.server.session.Session beginInvalidate
jenkins_1  | INFO: Session node01mxncqrs3hfpp1b33xu480awi00 already being invalidated

```

**Comment by arun-gupta** [comment]
@fabianenardon can the Jenkins setup be improved here?

**Comment by fabianenardon** [comment]
Best way to improve it is to add the new jenkins image to the list of images that should be downloaded before the lab. I opened a Pull Request for it: https://github.com/docker/labs/pull/367

@arun-gupta Can you approve the PR?

**Comment by arun-gupta** [comment]
Looks good, @ManoMarks will have to merge this.
