### ISSUE TITLE
Error while running  docker-compose up   while setting up In-container Java Development: Eclipse 

### ISSUE THREAD

**Issue by anilpank** [docker/labs#451]
I was following instructions from https://github.com/docker/labs/blob/master/developer-tools/java-debugging/Eclipse-README.md

My environment is WIndows 10 Enterprise.
My  Docker version 18.09.1, build 4c52b90

When I run the following command `docker-compose up` , I get the following error

java-debugging_webserver_1 exited with code 1
java-debugging_webserver_1 exited with code 1
Exception in thread Thread-7:
Traceback (most recent call last):
  File "site-packages\docker\api\client.py", line 246, in _raise_for_status
  File "site-packages\requests\models.py", line 940, in raise_for_status
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localnpipe/v1.22/containers/3c13d7f2fa436b4be8af3e4d13c4ed5b591b0a19b73da4f6f63fa8586b39cfce/attach?logs=0&stdout=1&stderr=1&stream=1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "compose\cli\log_printer.py", line 233, in watch_events
  File "compose\container.py", line 215, in attach_log_stream
  File "compose\container.py", line 307, in attach
  File "site-packages\docker\utils\decorators.py", line 19, in wrapped
  File "site-packages\docker\api\container.py", line 57, in attach
  File "site-packages\docker\api\client.py", line 385, in _read_from_socket
  File "site-packages\docker\api\client.py", line 296, in _get_raw_response_socket
  File "site-packages\docker\api\client.py", line 248, in _raise_for_status
  File "site-packages\docker\errors.py", line 19, in create_api_error_from_http_exception
  File "site-packages\requests\models.py", line 880, in json
  File "site-packages\requests\models.py", line 828, in content
  File "site-packages\requests\models.py", line 750, in generate
  File "site-packages\urllib3\response.py", line 494, in stream
  File "site-packages\urllib3\response.py", line 442, in read
  File "http\client.py", line 449, in read
  File "http\client.py", line 493, in readinto
  File "site-packages\docker\transport\npipesocket.py", line 209, in readinto
  File "site-packages\docker\transport\npipesocket.py", line 20, in wrapped
RuntimeError: Can not reuse socket after connection was closed.

Please let me know what I am doing wrong.

**Comment by viniciobb** [comment]
Same error !

**Comment by Lavaong** [comment]
same error,

**Comment by niaomingjian** [comment]
In my case changed line ending from CRLF to LF for the `run.sh` file because `Auto CrLf convert` wasn't set in  my TortoiseGit tool.
